name: Release Databases

on:
  push:
  #   tags:
  #   - '*'
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: |
          yarn install

      - name: Generate Databases
        working-directory: worker
        run: |
          mkdir -p tmp
          yarn ts-node src/CreateDbFilePerLanguage.ts

      - name: Create Python Release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e
        with:
          artifacts: "output/PyPI.json"
          name: ${{github.sha}}
          makeLatest: true
